name: Run

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      
    services:
        eskin:
          image: nginx:latest
          ports:
            # 将容器的 80 端口映射到主机的 8080 端口
            - 2333:2333
          
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yaml --name base
    - name: Run script
      run: |
        python src/test_server.py
